
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.demo
{
public partial class TbReward
{
    private readonly System.Collections.Generic.Dictionary<int, demo.Reward> _dataMap;
    private readonly System.Collections.Generic.List<demo.Reward> _dataList;
    
    public TbReward(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.Reward>(n);
        _dataList = new System.Collections.Generic.List<demo.Reward>(n);
        for(int i = n ; i > 0 ; --i)
        {
            demo.Reward _v;
            _v = global::GameConfig.demo.Reward.DeserializeReward(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, demo.Reward> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<demo.Reward> DataList => _dataList;

    public demo.Reward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.Reward Get(int key) => _dataMap[key];
    public demo.Reward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

