using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

[Generator]
public class EventInterfaceGenerator : ISourceGenerator
{
	public void Initialize(GeneratorInitializationContext context)
	{
	}

	public void Execute(GeneratorExecutionContext context)
	{
		//IL_00b3: Unknown result type (might be due to invalid IL or missing references)
		//IL_00b8: Unknown result type (might be due to invalid IL or missing references)
		//IL_017e: Unknown result type (might be due to invalid IL or missing references)
		if (context.Compilation.Assembly.Name != "GameLogic")
		{
			return;
		}
		IEnumerable<SyntaxTree> syntaxTrees = context.Compilation.SyntaxTrees;
		List<string> list = new List<string>();
		foreach (SyntaxTree item in syntaxTrees)
		{
			SyntaxNode root = item.GetRoot(default(CancellationToken));
			IEnumerable<InterfaceDeclarationSyntax> enumerable = from i in root.DescendantNodes((Func<SyntaxNode, bool>)null, false).OfType<InterfaceDeclarationSyntax>()
				where ((MemberDeclarationSyntax)i).AttributeLists.Count > 0 && ((IEnumerable<AttributeListSyntax>)(object)((MemberDeclarationSyntax)i).AttributeLists).Any((AttributeListSyntax a) => ((IEnumerable<AttributeSyntax>)(object)a.Attributes).Any((AttributeSyntax attr) => ((object)attr.Name).ToString() == "EventInterface"))
				select i;
			foreach (InterfaceDeclarationSyntax item2 in enumerable)
			{
				string text = ((object)((BaseTypeDeclarationSyntax)item2).Identifier/*cast due to .constrained prefix*/).ToString();
				string interfaceFullName = (from ns in ((SyntaxNode)item2).SyntaxTree.GetRoot(default(CancellationToken)).DescendantNodes((Func<SyntaxNode, bool>)null, false).OfType<NamespaceDeclarationSyntax>()
					select ((object)ns.Name).ToString()).Concat<string>(new string[1] { text }).Aggregate((string a, string b) => a + "." + b);
				string text2 = text + "_Event";
				string text3 = GenerateEventClass(text, text2, item2);
				context.AddSource(text2 + ".g.cs", text3);
				string text4 = GenerateImplementationClass(interfaceFullName, text, item2, context);
				context.AddSource(text + "_Gen.g.cs", text4);
				list.Add(text + "_Gen");
			}
		}
		string text5 = "GameEventHelper.g.cs";
		context.AddSource(text5, GenerateGameEventHelper(list));
	}

	private string GenerateGameEventHelper(List<string> classNameList)
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.AppendLine("//------------------------------------------------------------------------------");
		stringBuilder.AppendLine("//  <auto-generated>");
		stringBuilder.AppendLine("//     This code was generated by autoBindTool.");
		stringBuilder.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
		stringBuilder.AppendLine("//     the code is regenerated.");
		stringBuilder.AppendLine("//  </auto-generated>");
		stringBuilder.AppendLine("//------------------------------------------------------------------------------");
		stringBuilder.AppendLine();
		stringBuilder.AppendLine("using UnityEngine;");
		stringBuilder.AppendLine("using UnityEngine.UI;");
		stringBuilder.AppendLine("using TEngine;");
		stringBuilder.AppendLine();
		stringBuilder.AppendLine("namespace GameLogic");
		stringBuilder.AppendLine("{");
		stringBuilder.AppendLine("    public static class GameEventHelper");
		stringBuilder.AppendLine("    {");
		stringBuilder.AppendLine("        public static void Init()");
		stringBuilder.AppendLine("        {");
		foreach (string className in classNameList)
		{
			stringBuilder.AppendLine("            var m_" + className + " = new " + className + "(GameEvent.EventMgr.GetDispatcher());");
		}
		stringBuilder.AppendLine("        }");
		stringBuilder.AppendLine("    }");
		stringBuilder.AppendLine("}");
		return stringBuilder.ToString();
	}

	private string GenerateEventClass(string interfaceName, string className, InterfaceDeclarationSyntax interfaceNode)
	{
		//IL_0002: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ea: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ef: Unknown result type (might be due to invalid IL or missing references)
		//IL_010b: Unknown result type (might be due to invalid IL or missing references)
		IEnumerable<MethodDeclarationSyntax> enumerable = ((IEnumerable)(object)((TypeDeclarationSyntax)interfaceNode).Members).OfType<MethodDeclarationSyntax>();
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.AppendLine("//------------------------------------------------------------------------------");
		stringBuilder.AppendLine("//\t<auto-generated>");
		stringBuilder.AppendLine("//\t\tThis code was generated by autoBindTool.");
		stringBuilder.AppendLine("//\t\tChanges to this file may cause incorrect behavior and will be lost if");
		stringBuilder.AppendLine("//\t\tthe code is regenerated.");
		stringBuilder.AppendLine("//\t</auto-generated>");
		stringBuilder.AppendLine("//------------------------------------------------------------------------------");
		stringBuilder.AppendLine();
		stringBuilder.AppendLine("using UnityEngine;");
		stringBuilder.AppendLine("using UnityEngine.UI;");
		stringBuilder.AppendLine("using TEngine;");
		stringBuilder.AppendLine();
		stringBuilder.AppendLine("namespace GameLogic");
		stringBuilder.AppendLine("{");
		stringBuilder.AppendLine("    public partial class " + className);
		stringBuilder.AppendLine("    {");
		foreach (MethodDeclarationSyntax item in enumerable)
		{
			string text = ((object)item.Identifier/*cast due to .constrained prefix*/).ToString();
			string text2 = string.Join(", ", ((IEnumerable<ParameterSyntax>)(object)((BaseParameterListSyntax)((BaseMethodDeclarationSyntax)item).ParameterList).Parameters).Select((ParameterSyntax p) => $"{((BaseParameterSyntax)p).Type} {p.Identifier}"));
			stringBuilder.AppendLine("        public static readonly int " + text + " = RuntimeId.ToRuntimeId(\"" + className + "." + text + "\");");
		}
		stringBuilder.AppendLine("    }");
		stringBuilder.AppendLine("}");
		return stringBuilder.ToString();
	}

	private string GenerateImplementationClass(string interfaceFullName, string interfaceName, InterfaceDeclarationSyntax interfaceNode, GeneratorExecutionContext context)
	{
		//IL_013d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0160: Unknown result type (might be due to invalid IL or missing references)
		//IL_0165: Unknown result type (might be due to invalid IL or missing references)
		//IL_01c6: Unknown result type (might be due to invalid IL or missing references)
		//IL_01cb: Unknown result type (might be due to invalid IL or missing references)
		//IL_01ec: Unknown result type (might be due to invalid IL or missing references)
		SemanticModel semanticModel = context.Compilation.GetSemanticModel(interfaceNode.SyntaxTree, false);
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.AppendLine("//------------------------------------------------------------------------------");
		stringBuilder.AppendLine("//\t<auto-generated>");
		stringBuilder.AppendLine("//\t\tThis code was generated by autoBindTool.");
		stringBuilder.AppendLine("//\t\tChanges to this file may cause incorrect behavior and will be lost if");
		stringBuilder.AppendLine("//\t\tthe code is regenerated.");
		stringBuilder.AppendLine("//\t</auto-generated>");
		stringBuilder.AppendLine("//------------------------------------------------------------------------------");
		stringBuilder.AppendLine();
		stringBuilder.AppendLine("using UnityEngine;");
		stringBuilder.AppendLine("using UnityEngine.UI;");
		stringBuilder.AppendLine("using TEngine;");
		stringBuilder.AppendLine();
		stringBuilder.AppendLine("namespace GameLogic");
		stringBuilder.AppendLine("{");
		stringBuilder.AppendLine("    public partial class " + interfaceName + "_Gen : " + interfaceName);
		stringBuilder.AppendLine("    {");
		stringBuilder.AppendLine("        private EventDispatcher _dispatcher;");
		stringBuilder.AppendLine("        public " + interfaceName + "_Gen(EventDispatcher dispatcher)");
		stringBuilder.AppendLine("        {");
		stringBuilder.AppendLine("            _dispatcher = dispatcher;");
		stringBuilder.AppendLine("             GameEvent.EventMgr.RegWrapInterface(\"" + interfaceFullName + "\", this);");
		stringBuilder.AppendLine("        }");
		foreach (MethodDeclarationSyntax item in ((IEnumerable)(object)((TypeDeclarationSyntax)interfaceNode).Members).OfType<MethodDeclarationSyntax>())
		{
			string text = ((object)item.Identifier/*cast due to .constrained prefix*/).ToString();
			string text2 = GenerateParameters(item, semanticModel);
			stringBuilder.AppendLine("        public void " + text + "(" + text2 + ")");
			stringBuilder.AppendLine("        {");
			if (((BaseParameterListSyntax)((BaseMethodDeclarationSyntax)item).ParameterList).Parameters.Count > 0)
			{
				string text3 = string.Join(", ", ((IEnumerable<ParameterSyntax>)(object)((BaseParameterListSyntax)((BaseMethodDeclarationSyntax)item).ParameterList).Parameters).Select((ParameterSyntax p) => ((object)p.Identifier/*cast due to .constrained prefix*/).ToString()));
				stringBuilder.AppendLine("            _dispatcher.Send(" + interfaceName + "_Event." + text + ", " + text3 + ");");
			}
			else
			{
				stringBuilder.AppendLine("            _dispatcher.Send(" + interfaceName + "_Event." + text + ");");
			}
			stringBuilder.AppendLine("        }");
		}
		stringBuilder.AppendLine("    }");
		stringBuilder.AppendLine("}");
		return stringBuilder.ToString();
	}

	private string GenerateParameters(MethodDeclarationSyntax method, SemanticModel semanticModel)
	{
		//IL_0019: Unknown result type (might be due to invalid IL or missing references)
		return string.Join(", ", ((IEnumerable<ParameterSyntax>)(object)((BaseParameterListSyntax)((BaseMethodDeclarationSyntax)method).ParameterList).Parameters).Select(delegate(ParameterSyntax p)
		{
			//IL_0016: Unknown result type (might be due to invalid IL or missing references)
			//IL_001b: Unknown result type (might be due to invalid IL or missing references)
			//IL_0051: Unknown result type (might be due to invalid IL or missing references)
			//IL_0033: Unknown result type (might be due to invalid IL or missing references)
			TypeInfo typeInfo = Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetTypeInfo(semanticModel, (ExpressionSyntax)(object)((BaseParameterSyntax)p).Type, default(CancellationToken));
			ITypeSymbol type = typeInfo.Type;
			return (type != null) ? $"{((ISymbol)type).ToDisplayString((SymbolDisplayFormat)null)} {p.Identifier}" : $"{((BaseParameterSyntax)p).Type} {p.Identifier}";
		}));
	}
}
